os: linux
services:
  - mysql
before_script:
  - cp config/database.yml.travis config/database.yml
dist: bionic
language: ruby
rvm:
  - 2.6.3
script:
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rspec