os: linux
services:
  - mysql
before_script:
  - cp config/database.yml.travis config/database.yml
before_install:
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
dist: bionic
language: ruby
rvm:
  - 2.6.3
script:
  - yarn install
  - bundle exec rails db:setup RAILS_ENV=test
  - bundle exec rails db:migrate RAILS_ENV=test
  - bundle exec rspec